language: csharp
solution: AuthTesting.sln

mono:
  - latest
  - 3.12.0
  - 3.10.0
  
install:
  - dotnet restore

script: 
  - dotnet build
  - dotnet C:\Users\Marco Leon\source\repos\AuthTesting.csproj
